apiVersion: v1
kind: ConfigMap
metadata:
  name: wrongsecrets-balancer-config
  labels:
    helm.sh/chart: {{ include "wrongsecrets-ctf-party.chart" . }}
data:
  config.json: |
    {
      "port": {{ .Values.balancer.containerPort }},
      "namespace": {{ .Release.Namespace | quote }},
      "deploymentContext": {{ .Release.Name | quote }},
      "maxJuiceShopInstances": {{ .Values.wrongsecrets.maxInstances}},
      "skipOwnerReference": {{ .Values.balancer.skipOwnerReference }},
      "cookieParser": {
        "cookieName": {{ include "wrongsecrets-ctf-party.cookieName" . | quote }},
        "secure": {{ .Values.balancer.cookie.secure }}
      },
      "admin": {
        "username": {{ .Values.balancer.basicAuth.username | quote }}
      },
      "wrongsecrets": {
        "image": {{ .Values.wrongsecrets.image | quote }},
        "tag": {{ .Values.wrongsecrets.tag | quote }},
        "imagePullPolicy": {{ .Values.imagePullPolicy | quote }},
        "ctfKey": {{ .Values.wrongsecrets.ctfKey | quote }},
        "nodeEnv": {{ .Values.wrongsecrets.nodeEnv | quote }},
        "resources": {{ .Values.wrongsecrets.resources | toJson }},
        "securityContext": {{ .Values.wrongsecrets.securityContext | toJson }},
        "env": {{ .Values.wrongsecrets.env | toJson }},
        "envFrom": {{ .Values.wrongsecrets.envFrom | toJson }},
        "volumes": {{ .Values.wrongsecrets.volumes | toJson }},
        "volumeMounts": {{ .Values.wrongsecrets.volumeMounts | toJson }},
        "affinity": {{ .Values.wrongsecrets.affinity | toJson }},
        "tolerations": {{ .Values.wrongsecrets.tolerations | toJson }},
        "runtimeClassName": {{ .Values.wrongsecrets.runtimeClassName | toJson }}
      },
      "websocket": {
        "servicename1:8080": [
          "incomingurl1",
          "incomingurl2",
          "incomingurl3"
        ],
        "serviname2:3000": [
          "incomingurl4",
          "incomingurl5"
        ]
      },
      "proxy": {
        "servicename1:8080": [
          "incomingurl6",
          "incomingurl7"
        ],
        "servicename2:3000": [
          "incomingurl8withwildcard"
        ],
        "servicename3(CTFD)": [
          "incomingurl9",
          "incomingurl10"
        ],
        "servicename4(grafana)": [
          "incomingurl10"
        ]
      }
    }